os: osx
language: node_js
node_js: 
  - "lts/*"

addons:
apt:
  packages:
    # needed by Cypress, not in Ubuntu 16+ by default
    - libgconf-2-4

cache:
  directories:
    - node_modules
    # folder with Cypress binary
    - ~/.cache

branches:
  only:
  - master

stages:
  - Build and run unit tests
  - End to end tests

jobs:
  include:
    - stage: Build and run unit tests
      script: 
      - npm run build
      - npm run test
    - stage: End to end tests
      script:
        - npm run test:ci

notifications:
  slack:
    rooms: generositymarket:ZeAVzH5Ww7PB50ugNnwl5JuT#cs-react-builds
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: "
      - "```%{commit_message}```"

# deploy:
#   provider: pages
#   github_token: $github_token
#   skip_cleanup: true
#   local_dir: build
#   on:
#     branch: master