os: osx
language: node_js
node_js: 
  - "lts/*"
cache:
  directories:
    - node_modules

branches:
  only:
  - master

script: 
  - npm test
  - npm run build

notifications:
  slack:
    rooms: generositymarket:ZeAVzH5Ww7PB50ugNnwl5JuT#cs-react-builds
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: "
      - "```%{commit_message}```"

# deploy:
#   provider: pages
#   github_token: $github_token
#   skip_cleanup: true
#   local_dir: build
#   on:
#     branch: master