language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - node_modules
script: 
  - npm test
  - npm build
deploy:
  provider: pages
  # github_token: $github_token
  skip_cleanup: true
  local_dir: build
  on:
    branch: master